-- Seed data untuk tabel obat (300 data)
USE baksos_db;

INSERT INTO obat (nama_obat, satuan, stok, keterangan) VALUES
('Paracetamol', 'tablet', 1000, 'Obat pereda nyeri dan demam'),
('Amoxicillin', 'kapsul', 500, 'Antibiotik untuk infeksi bakteri'),
('CTM (Chlorpheniramine)', 'tablet', 800, 'Obat alergi dan pilek'),
('Ibuprofen', 'tablet', 600, 'Obat antiinflamasi dan pereda nyeri'),
('Metformin', 'tablet', 400, 'Obat diabetes tipe 2'),
('Amlodipine', 'tablet', 500, 'Obat hipertensi'),
('Omeprazole', 'kapsul', 450, 'Obat maag dan GERD'),
('Loratadine', 'tablet', 700, 'Obat alergi'),
('Salbutamol', 'inhaler', 300, 'Obat asma'),
('Furosemide', 'tablet', 350, 'Obat diuretik untuk hipertensi'),
('Simvastatin', 'tablet', 400, 'Obat kolesterol'),
('Metronidazole', 'tablet', 500, 'Antibiotik untuk infeksi'),
('Ciprofloxacin', 'tablet', 400, 'Antibiotik spektrum luas'),
('Dexamethasone', 'tablet', 300, 'Obat antiinflamasi steroid'),
('Ranitidine', 'tablet', 500, 'Obat maag'),
('Captopril', 'tablet', 450, 'Obat hipertensi'),
('Losartan', 'tablet', 400, 'Obat hipertensi'),
('Atenolol', 'tablet', 500, 'Obat hipertensi dan jantung'),
('Folic Acid', 'tablet', 1000, 'Suplemen asam folat'),
('Vitamin C', 'tablet', 1500, 'Suplemen vitamin C'),
('Vitamin D', 'kapsul', 800, 'Suplemen vitamin D'),
('Calcium', 'tablet', 900, 'Suplemen kalsium'),
('Iron (Fe)', 'tablet', 700, 'Suplemen zat besi'),
('Multivitamin', 'tablet', 1200, 'Suplemen multivitamin'),
('Zinc', 'tablet', 600, 'Suplemen zinc'),
('Doxycycline', 'kapsul', 400, 'Antibiotik'),
('Azithromycin', 'tablet', 350, 'Antibiotik'),
('Cefadroxil', 'kapsul', 450, 'Antibiotik'),
('Erythromycin', 'tablet', 400, 'Antibiotik'),
('Clindamycin', 'kapsul', 300, 'Antibiotik'),
('Diclofenac', 'tablet', 500, 'Obat antiinflamasi'),
('Mefenamic Acid', 'kapsul', 600, 'Obat pereda nyeri'),
('Tramadol', 'tablet', 200, 'Obat pereda nyeri kuat'),
('Morphine', 'injeksi', 50, 'Obat pereda nyeri sangat kuat'),
('Codeine', 'tablet', 150, 'Obat batuk dan pereda nyeri'),
('Dextromethorphan', 'sirup', 400, 'Obat batuk'),
('Guaifenesin', 'sirup', 350, 'Obat batuk berdahak'),
('Bromhexine', 'tablet', 500, 'Obat batuk berdahak'),
('Ambroxol', 'sirup', 450, 'Obat batuk berdahak'),
('Cetirizine', 'tablet', 700, 'Obat alergi'),
('Diphenhydramine', 'tablet', 500, 'Obat alergi dan tidur'),
('Promethazine', 'tablet', 400, 'Obat alergi dan mual'),
('Metoclopramide', 'tablet', 500, 'Obat mual dan muntah'),
('Domperidone', 'tablet', 450, 'Obat mual dan muntah'),
('Ondansetron', 'tablet', 300, 'Obat mual dan muntah'),
('Loperamide', 'kapsul', 600, 'Obat diare'),
('Kaolin Pectin', 'sirup', 500, 'Obat diare'),
('Bismuth Subsalicylate', 'tablet', 400, 'Obat diare'),
('Lactobacillus', 'kapsul', 800, 'Probiotik untuk pencernaan'),
('Bisacodyl', 'tablet', 500, 'Obat sembelit'),
('Psyllium Husk', 'sachet', 600, 'Serat untuk sembelit'),
('Glycerin Suppository', 'suppositoria', 400, 'Obat sembelit'),
('Antasida', 'tablet', 1000, 'Obat maag'),
('Sucralfate', 'tablet', 400, 'Obat maag'),
('Lansoprazole', 'kapsul', 350, 'Obat maag'),
('Pantoprazole', 'tablet', 400, 'Obat maag'),
('Esomeprazole', 'kapsul', 300, 'Obat maag'),
('Famotidine', 'tablet', 450, 'Obat maag'),
('Bismuth Subcitrate', 'tablet', 400, 'Obat maag'),
('Aluminum Hydroxide', 'tablet', 500, 'Antasida'),
('Magnesium Hydroxide', 'tablet', 500, 'Antasida'),
('Simethicone', 'tablet', 600, 'Obat kembung'),
('Activated Charcoal', 'kapsul', 400, 'Obat keracunan'),
('Nystatin', 'tablet', 500, 'Obat jamur'),
('Fluconazole', 'kapsul', 400, 'Obat jamur'),
('Ketoconazole', 'tablet', 300, 'Obat jamur'),
('Miconazole', 'krim', 500, 'Obat jamur topikal'),
('Clotrimazole', 'krim', 600, 'Obat jamur topikal'),
('Terbinafine', 'tablet', 350, 'Obat jamur'),
('Acyclovir', 'tablet', 400, 'Obat antivirus herpes'),
('Valacyclovir', 'tablet', 300, 'Obat antivirus herpes'),
('Oseltamivir', 'kapsul', 200, 'Obat antivirus flu'),
('Ribavirin', 'tablet', 150, 'Obat antivirus'),
('Atenolol', 'tablet', 500, 'Obat jantung'),
('Propranolol', 'tablet', 450, 'Obat jantung dan hipertensi'),
('Metoprolol', 'tablet', 400, 'Obat jantung'),
('Carvedilol', 'tablet', 350, 'Obat jantung'),
('Digoxin', 'tablet', 300, 'Obat jantung'),
('Furosemide', 'tablet', 500, 'Obat diuretik'),
('Hydrochlorothiazide', 'tablet', 600, 'Obat diuretik'),
('Spironolactone', 'tablet', 400, 'Obat diuretik'),
('Triamterene', 'tablet', 350, 'Obat diuretik'),
('Mannitol', 'injeksi', 200, 'Obat diuretik'),
('Warfarin', 'tablet', 300, 'Obat pengencer darah'),
('Aspirin', 'tablet', 1000, 'Obat pengencer darah'),
('Clopidogrel', 'tablet', 400, 'Obat pengencer darah'),
('Heparin', 'injeksi', 250, 'Obat pengencer darah'),
('Enoxaparin', 'injeksi', 200, 'Obat pengencer darah'),
('Atorvastatin', 'tablet', 500, 'Obat kolesterol'),
('Rosuvastatin', 'tablet', 400, 'Obat kolesterol'),
('Pravastatin', 'tablet', 350, 'Obat kolesterol'),
('Fenofibrate', 'kapsul', 300, 'Obat kolesterol'),
('Gemfibrozil', 'tablet', 300, 'Obat kolesterol'),
('Insulin Regular', 'injeksi', 200, 'Obat diabetes'),
('Insulin NPH', 'injeksi', 200, 'Obat diabetes'),
('Insulin Glargine', 'injeksi', 150, 'Obat diabetes'),
('Glibenclamide', 'tablet', 500, 'Obat diabetes'),
('Gliclazide', 'tablet', 450, 'Obat diabetes'),
('Glimepiride', 'tablet', 400, 'Obat diabetes'),
('Pioglitazone', 'tablet', 300, 'Obat diabetes'),
('Sitagliptin', 'tablet', 350, 'Obat diabetes'),
('Acarbose', 'tablet', 400, 'Obat diabetes'),
('Levothyroxine', 'tablet', 500, 'Obat tiroid'),
('Methimazole', 'tablet', 300, 'Obat hipertiroid'),
('Propylthiouracil', 'tablet', 250, 'Obat hipertiroid'),
('Prednisone', 'tablet', 400, 'Obat steroid'),
('Methylprednisolone', 'tablet', 350, 'Obat steroid'),
('Hydrocortisone', 'krim', 500, 'Obat steroid topikal'),
('Betamethasone', 'krim', 450, 'Obat steroid topikal'),
('Triamcinolone', 'krim', 400, 'Obat steroid topikal'),
('Estradiol', 'tablet', 300, 'Obat hormon wanita'),
('Progesterone', 'tablet', 300, 'Obat hormon wanita'),
('Levonorgestrel', 'tablet', 400, 'Kontrasepsi'),
('Ethinyl Estradiol', 'tablet', 350, 'Kontrasepsi'),
('Medroxyprogesterone', 'tablet', 300, 'Kontrasepsi'),
('Testosterone', 'injeksi', 200, 'Obat hormon pria'),
('Finasteride', 'tablet', 300, 'Obat prostat'),
('Tamsulosin', 'kapsul', 400, 'Obat prostat'),
('Sildenafil', 'tablet', 200, 'Obat disfungsi ereksi'),
('Tadalafil', 'tablet', 200, 'Obat disfungsi ereksi'),
('Allopurinol', 'tablet', 400, 'Obat asam urat'),
('Colchicine', 'tablet', 300, 'Obat asam urat'),
('Probenecid', 'tablet', 250, 'Obat asam urat'),
('Methotrexate', 'tablet', 200, 'Obat rematik'),
('Sulfasalazine', 'tablet', 300, 'Obat rematik'),
('Hydroxychloroquine', 'tablet', 250, 'Obat rematik'),
('Cyclophosphamide', 'tablet', 150, 'Obat imunosupresan'),
('Azathioprine', 'tablet', 200, 'Obat imunosupresan'),
('Tacrolimus', 'kapsul', 150, 'Obat imunosupresan'),
('Cyclosporine', 'kapsul', 150, 'Obat imunosupresan'),
('Mycophenolate', 'tablet', 200, 'Obat imunosupresan'),
('Phenytoin', 'tablet', 400, 'Obat epilepsi'),
('Carbamazepine', 'tablet', 350, 'Obat epilepsi'),
('Valproic Acid', 'tablet', 400, 'Obat epilepsi'),
('Levetiracetam', 'tablet', 300, 'Obat epilepsi'),
('Gabapentin', 'kapsul', 400, 'Obat epilepsi dan nyeri'),
('Pregabalin', 'kapsul', 300, 'Obat epilepsi dan nyeri'),
('Amitriptyline', 'tablet', 400, 'Obat depresi'),
('Fluoxetine', 'kapsul', 500, 'Obat depresi'),
('Sertraline', 'tablet', 450, 'Obat depresi'),
('Paroxetine', 'tablet', 400, 'Obat depresi'),
('Citalopram', 'tablet', 400, 'Obat depresi'),
('Escitalopram', 'tablet', 350, 'Obat depresi'),
('Venlafaxine', 'kapsul', 300, 'Obat depresi'),
('Duloxetine', 'kapsul', 300, 'Obat depresi'),
('Imipramine', 'tablet', 300, 'Obat depresi'),
('Clomipramine', 'tablet', 250, 'Obat depresi'),
('Haloperidol', 'tablet', 300, 'Obat antipsikotik'),
('Risperidone', 'tablet', 350, 'Obat antipsikotik'),
('Olanzapine', 'tablet', 300, 'Obat antipsikotik'),
('Quetiapine', 'tablet', 300, 'Obat antipsikotik'),
('Aripiprazole', 'tablet', 250, 'Obat antipsikotik'),
('Clozapine', 'tablet', 200, 'Obat antipsikotik'),
('Lithium', 'tablet', 300, 'Obat gangguan bipolar'),
('Diazepam', 'tablet', 400, 'Obat ansietas'),
('Alprazolam', 'tablet', 350, 'Obat ansietas'),
('Lorazepam', 'tablet', 300, 'Obat ansietas'),
('Clonazepam', 'tablet', 300, 'Obat ansietas dan epilepsi'),
('Buspirone', 'tablet', 250, 'Obat ansietas'),
('Zolpidem', 'tablet', 400, 'Obat tidur'),
('Zaleplon', 'tablet', 300, 'Obat tidur'),
('Eszopiclone', 'tablet', 250, 'Obat tidur'),
('Melatonin', 'tablet', 600, 'Obat tidur alami'),
('Donepezil', 'tablet', 300, 'Obat demensia'),
('Memantine', 'tablet', 250, 'Obat demensia'),
('Rivastigmine', 'kapsul', 200, 'Obat demensia'),
('Galantamine', 'tablet', 200, 'Obat demensia'),
('Levodopa', 'tablet', 300, 'Obat Parkinson'),
('Carbidopa', 'tablet', 300, 'Obat Parkinson'),
('Pramipexole', 'tablet', 250, 'Obat Parkinson'),
('Ropinirole', 'tablet', 250, 'Obat Parkinson'),
('Benztropine', 'tablet', 300, 'Obat Parkinson'),
('Tolterodine', 'kapsul', 400, 'Obat kandung kemih'),
('Oxybutynin', 'tablet', 400, 'Obat kandung kemih'),
('Solifenacin', 'tablet', 300, 'Obat kandung kemih'),
('Mirabegron', 'tablet', 250, 'Obat kandung kemih'),
('Tamsulosin', 'kapsul', 400, 'Obat prostat'),
('Dutasteride', 'kapsul', 300, 'Obat prostat'),
('Alfuzosin', 'tablet', 300, 'Obat prostat'),
('Terazosin', 'tablet', 300, 'Obat prostat'),
('Doxazosin', 'tablet', 300, 'Obat prostat'),
('Tadalafil', 'tablet', 200, 'Obat disfungsi ereksi'),
('Sildenafil', 'tablet', 200, 'Obat disfungsi ereksi'),
('Vardenafil', 'tablet', 150, 'Obat disfungsi ereksi'),
('Alprostadil', 'injeksi', 100, 'Obat disfungsi ereksi'),
('Papaverine', 'injeksi', 100, 'Obat disfungsi ereksi'),
('Misoprostol', 'tablet', 300, 'Obat lambung dan induksi persalinan'),
('Oxytocin', 'injeksi', 200, 'Obat induksi persalinan'),
('Methylergometrine', 'tablet', 300, 'Obat kontraksi rahim'),
('Ergometrine', 'injeksi', 200, 'Obat kontraksi rahim'),
('Dinoprostone', 'gel', 150, 'Obat induksi persalinan'),
('Clomiphene', 'tablet', 200, 'Obat kesuburan'),
('Letrozole', 'tablet', 200, 'Obat kesuburan'),
('Tamoxifen', 'tablet', 250, 'Obat kanker payudara'),
('Anastrozole', 'tablet', 200, 'Obat kanker payudara'),
('Exemestane', 'tablet', 200, 'Obat kanker payudara'),
('Goserelin', 'injeksi', 150, 'Obat kanker'),
('Leuprolide', 'injeksi', 150, 'Obat kanker'),
('Bicalutamide', 'tablet', 200, 'Obat kanker prostat'),
('Flutamide', 'tablet', 200, 'Obat kanker prostat'),
('Nilutamide', 'tablet', 150, 'Obat kanker prostat'),
('Methotrexate', 'tablet', 200, 'Obat kanker'),
('5-Fluorouracil', 'injeksi', 150, 'Obat kanker'),
('Cyclophosphamide', 'tablet', 150, 'Obat kanker'),
('Doxorubicin', 'injeksi', 100, 'Obat kanker'),
('Cisplatin', 'injeksi', 100, 'Obat kanker'),
('Carboplatin', 'injeksi', 100, 'Obat kanker'),
('Paclitaxel', 'injeksi', 100, 'Obat kanker'),
('Docetaxel', 'injeksi', 100, 'Obat kanker'),
('Vincristine', 'injeksi', 100, 'Obat kanker'),
('Vinblastine', 'injeksi', 100, 'Obat kanker'),
('Etoposide', 'injeksi', 100, 'Obat kanker'),
('Irinotecan', 'injeksi', 100, 'Obat kanker'),
('Topotecan', 'injeksi', 100, 'Obat kanker'),
('Gemcitabine', 'injeksi', 100, 'Obat kanker'),
('Capecitabine', 'tablet', 150, 'Obat kanker'),
('Temozolomide', 'kapsul', 100, 'Obat kanker'),
('Imatinib', 'tablet', 100, 'Obat kanker'),
('Erlotinib', 'tablet', 100, 'Obat kanker'),
('Gefitinib', 'tablet', 100, 'Obat kanker'),
('Sorafenib', 'tablet', 100, 'Obat kanker'),
('Sunitinib', 'kapsul', 100, 'Obat kanker'),
('Pazopanib', 'tablet', 100, 'Obat kanker'),
('Rituximab', 'injeksi', 50, 'Obat kanker'),
('Trastuzumab', 'injeksi', 50, 'Obat kanker'),
('Bevacizumab', 'injeksi', 50, 'Obat kanker'),
('Cetuximab', 'injeksi', 50, 'Obat kanker'),
('Panitumumab', 'injeksi', 50, 'Obat kanker'),
('Pembrolizumab', 'injeksi', 30, 'Obat kanker'),
('Nivolumab', 'injeksi', 30, 'Obat kanker'),
('Atezolizumab', 'injeksi', 30, 'Obat kanker'),
('Durvalumab', 'injeksi', 30, 'Obat kanker'),
('Avelumab', 'injeksi', 30, 'Obat kanker'),
('Filgrastim', 'injeksi', 100, 'Obat neutropenia'),
('Pegfilgrastim', 'injeksi', 50, 'Obat neutropenia'),
('Epoetin Alfa', 'injeksi', 100, 'Obat anemia'),
('Darbepoetin Alfa', 'injeksi', 50, 'Obat anemia'),
('Iron Dextran', 'injeksi', 100, 'Obat anemia'),
('Iron Sucrose', 'injeksi', 100, 'Obat anemia'),
('Ferrous Sulfate', 'tablet', 800, 'Obat anemia'),
('Ferrous Fumarate', 'tablet', 700, 'Obat anemia'),
('Ferrous Gluconate', 'tablet', 600, 'Obat anemia'),
('Folic Acid', 'tablet', 1000, 'Obat anemia'),
('Cyanocobalamin', 'injeksi', 500, 'Obat anemia'),
('Hydroxocobalamin', 'injeksi', 400, 'Obat anemia'),
('Methylcobalamin', 'tablet', 500, 'Obat anemia'),
('Calcium Carbonate', 'tablet', 900, 'Suplemen kalsium'),
('Calcium Citrate', 'tablet', 800, 'Suplemen kalsium'),
('Calcium Lactate', 'tablet', 700, 'Suplemen kalsium'),
('Calcium Gluconate', 'injeksi', 300, 'Suplemen kalsium'),
('Cholecalciferol', 'kapsul', 800, 'Vitamin D3'),
('Ergocalciferol', 'kapsul', 700, 'Vitamin D2'),
('Calcitriol', 'kapsul', 400, 'Vitamin D aktif'),
('Alfacalcidol', 'kapsul', 400, 'Vitamin D aktif'),
('Ascorbic Acid', 'tablet', 1500, 'Vitamin C'),
('Thiamine', 'tablet', 800, 'Vitamin B1'),
('Riboflavin', 'tablet', 800, 'Vitamin B2'),
('Niacin', 'tablet', 700, 'Vitamin B3'),
('Pyridoxine', 'tablet', 800, 'Vitamin B6'),
('Biotin', 'tablet', 600, 'Vitamin B7'),
('Pantothenic Acid', 'tablet', 600, 'Vitamin B5'),
('Folic Acid', 'tablet', 1000, 'Vitamin B9'),
('Cyanocobalamin', 'injeksi', 500, 'Vitamin B12'),
('Multivitamin', 'tablet', 1200, 'Multivitamin'),
('Prenatal Vitamin', 'tablet', 500, 'Vitamin untuk ibu hamil'),
('Zinc Sulfate', 'tablet', 600, 'Suplemen zinc'),
('Zinc Gluconate', 'tablet', 500, 'Suplemen zinc'),
('Magnesium', 'tablet', 700, 'Suplemen magnesium'),
('Potassium Chloride', 'tablet', 600, 'Suplemen kalium'),
('Selenium', 'tablet', 500, 'Suplemen selenium'),
('Copper', 'tablet', 400, 'Suplemen tembaga'),
('Manganese', 'tablet', 400, 'Suplemen mangan'),
('Chromium', 'tablet', 400, 'Suplemen kromium'),
('Molybdenum', 'tablet', 300, 'Suplemen molibdenum'),
('Iodine', 'tablet', 500, 'Suplemen yodium'),
('Omega-3', 'kapsul', 600, 'Suplemen omega-3'),
('Coenzyme Q10', 'kapsul', 400, 'Suplemen CoQ10'),
('Glucosamine', 'tablet', 500, 'Suplemen sendi'),
('Chondroitin', 'tablet', 400, 'Suplemen sendi'),
('MSM', 'tablet', 400, 'Suplemen sendi'),
('Collagen', 'tablet', 300, 'Suplemen kolagen'),
('Probiotic', 'kapsul', 800, 'Probiotik'),
('Lactobacillus', 'kapsul', 800, 'Probiotik'),
('Bifidobacterium', 'kapsul', 700, 'Probiotik'),
('Saccharomyces', 'kapsul', 600, 'Probiotik'),
('Fiber Supplement', 'sachet', 500, 'Suplemen serat'),
('Psyllium', 'sachet', 600, 'Suplemen serat'),
('Inulin', 'sachet', 500, 'Suplemen serat'),
('Whey Protein', 'sachet', 400, 'Suplemen protein'),
('Casein Protein', 'sachet', 300, 'Suplemen protein'),
('Soy Protein', 'sachet', 300, 'Suplemen protein'),
('BCAA', 'tablet', 400, 'Suplemen asam amino'),
('Creatine', 'tablet', 300, 'Suplemen kreatin'),
('L-Carnitine', 'tablet', 400, 'Suplemen karnitin'),
('L-Arginine', 'tablet', 400, 'Suplemen arginin'),
('L-Glutamine', 'tablet', 400, 'Suplemen glutamin'),
('Taurine', 'tablet', 300, 'Suplemen taurin'),
('Tryptophan', 'tablet', 300, 'Suplemen triptofan'),
('5-HTP', 'tablet', 300, 'Suplemen 5-HTP'),
('SAM-e', 'tablet', 200, 'Suplemen SAM-e'),
('St. John\'s Wort', 'tablet', 400, 'Suplemen herbal'),
('Ginkgo Biloba', 'tablet', 500, 'Suplemen herbal'),
('Ginseng', 'kapsul', 400, 'Suplemen herbal'),
('Echinacea', 'tablet', 500, 'Suplemen herbal'),
('Turmeric', 'kapsul', 600, 'Suplemen herbal'),
('Ginger', 'kapsul', 500, 'Suplemen herbal'),
('Garlic', 'kapsul', 500, 'Suplemen herbal'),
('Green Tea Extract', 'tablet', 400, 'Suplemen herbal'),
('Milk Thistle', 'tablet', 400, 'Suplemen herbal'),
('Saw Palmetto', 'tablet', 300, 'Suplemen herbal'),
('Black Cohosh', 'tablet', 300, 'Suplemen herbal'),
('Evening Primrose Oil', 'kapsul', 300, 'Suplemen herbal'),
('Flaxseed Oil', 'kapsul', 400, 'Suplemen herbal'),
('Fish Oil', 'kapsul', 600, 'Suplemen minyak ikan'),
('Cod Liver Oil', 'kapsul', 500, 'Suplemen minyak ikan'),
('Krill Oil', 'kapsul', 300, 'Suplemen minyak krill'),
('Aloe Vera', 'gel', 500, 'Suplemen herbal'),
('Aloe Vera Juice', 'botol', 400, 'Suplemen herbal'),
('Cranberry', 'kapsul', 500, 'Suplemen herbal'),
('Bilberry', 'tablet', 400, 'Suplemen herbal'),
('Blueberry Extract', 'tablet', 300, 'Suplemen herbal'),
('Resveratrol', 'tablet', 300, 'Suplemen antioksidan'),
('Quercetin', 'tablet', 300, 'Suplemen antioksidan'),
('Lycopene', 'tablet', 300, 'Suplemen antioksidan'),
('Lutein', 'tablet', 400, 'Suplemen mata'),
('Zeaxanthin', 'tablet', 300, 'Suplemen mata'),
('Astaxanthin', 'kapsul', 300, 'Suplemen antioksidan'),
('Spirulina', 'tablet', 400, 'Suplemen alga'),
('Chlorella', 'tablet', 300, 'Suplemen alga'),
('Wheat Grass', 'tablet', 300, 'Suplemen herbal'),
('Barley Grass', 'tablet', 300, 'Suplemen herbal'),
('Moringa', 'kapsul', 400, 'Suplemen herbal'),
('Ashwagandha', 'tablet', 400, 'Suplemen herbal'),
('Rhodiola', 'tablet', 300, 'Suplemen herbal'),
('Bacopa', 'tablet', 300, 'Suplemen herbal'),
('Gotu Kola', 'tablet', 300, 'Suplemen herbal'),
('Brahmi', 'tablet', 300, 'Suplemen herbal'),
('Shankhpushpi', 'tablet', 300, 'Suplemen herbal'),
('Jatamansi', 'tablet', 300, 'Suplemen herbal'),
('Sarpagandha', 'tablet', 300, 'Suplemen herbal'),
('Arjuna', 'tablet', 300, 'Suplemen herbal'),
('Guggul', 'tablet', 300, 'Suplemen herbal'),
('Triphala', 'tablet', 400, 'Suplemen herbal'),
('Triphala Churna', 'sachet', 300, 'Suplemen herbal'),
('Amla', 'tablet', 500, 'Suplemen herbal'),
('Haritaki', 'tablet', 300, 'Suplemen herbal'),
('Bibhitaki', 'tablet', 300, 'Suplemen herbal'),
('Neem', 'tablet', 400, 'Suplemen herbal'),
('Tulsi', 'tablet', 500, 'Suplemen herbal'),
('Giloy', 'tablet', 400, 'Suplemen herbal'),
('Amla Juice', 'botol', 400, 'Suplemen herbal'),
('Aloe Vera Juice', 'botol', 400, 'Suplemen herbal'),
('Wheat Grass Juice', 'botol', 300, 'Suplemen herbal'),
('Barley Grass Juice', 'botol', 300, 'Suplemen herbal'),
('Moringa Powder', 'sachet', 400, 'Suplemen herbal'),
('Spirulina Powder', 'sachet', 300, 'Suplemen herbal'),
('Chlorella Powder', 'sachet', 300, 'Suplemen herbal'),
('Protein Powder', 'sachet', 400, 'Suplemen protein'),
('Mass Gainer', 'sachet', 300, 'Suplemen penambah berat'),
('Weight Gainer', 'sachet', 300, 'Suplemen penambah berat'),
('Fat Burner', 'tablet', 300, 'Suplemen pembakar lemak'),
('L-Carnitine', 'tablet', 400, 'Suplemen pembakar lemak'),
('CLA', 'kapsul', 300, 'Suplemen pembakar lemak'),
('Green Coffee Bean', 'kapsul', 300, 'Suplemen pembakar lemak'),
('Garcinia Cambogia', 'kapsul', 300, 'Suplemen pembakar lemak'),
('Raspberry Ketone', 'tablet', 300, 'Suplemen pembakar lemak'),
('Apple Cider Vinegar', 'tablet', 400, 'Suplemen kesehatan'),
('Apple Cider Vinegar', 'botol', 300, 'Suplemen kesehatan'),
('Coconut Oil', 'botol', 400, 'Suplemen minyak kelapa'),
('Olive Oil', 'botol', 300, 'Suplemen minyak zaitun'),
('Avocado Oil', 'botol', 300, 'Suplemen minyak alpukat'),
('Hemp Oil', 'botol', 200, 'Suplemen minyak hemp'),
('MCT Oil', 'botol', 200, 'Suplemen MCT oil'),
('CBD Oil', 'botol', 100, 'Suplemen CBD'),
('Hemp Seed Oil', 'botol', 200, 'Suplemen minyak biji hemp'),
('Pumpkin Seed Oil', 'botol', 200, 'Suplemen minyak biji labu'),
('Sunflower Seed Oil', 'botol', 200, 'Suplemen minyak biji bunga matahari'),
('Sesame Oil', 'botol', 200, 'Suplemen minyak wijen'),
('Grapeseed Oil', 'botol', 200, 'Suplemen minyak biji anggur'),
('Rosehip Oil', 'botol', 200, 'Suplemen minyak rosehip'),
('Jojoba Oil', 'botol', 200, 'Suplemen minyak jojoba'),
('Argan Oil', 'botol', 200, 'Suplemen minyak argan'),
('Tea Tree Oil', 'botol', 300, 'Suplemen minyak tea tree'),
('Eucalyptus Oil', 'botol', 300, 'Suplemen minyak eukaliptus'),
('Peppermint Oil', 'botol', 300, 'Suplemen minyak peppermint'),
('Lavender Oil', 'botol', 300, 'Suplemen minyak lavender'),
('Lemon Oil', 'botol', 300, 'Suplemen minyak lemon'),
('Orange Oil', 'botol', 300, 'Suplemen minyak jeruk'),
('Bergamot Oil', 'botol', 200, 'Suplemen minyak bergamot'),
('Ylang-Ylang Oil', 'botol', 200, 'Suplemen minyak ylang-ylang'),
('Chamomile Oil', 'botol', 200, 'Suplemen minyak chamomile'),
('Frankincense Oil', 'botol', 200, 'Suplemen minyak frankincense'),
('Myrrh Oil', 'botol', 200, 'Suplemen minyak myrrh'),
('Sandalwood Oil', 'botol', 200, 'Suplemen minyak sandalwood'),
('Patchouli Oil', 'botol', 200, 'Suplemen minyak patchouli'),
('Geranium Oil', 'botol', 200, 'Suplemen minyak geranium'),
('Jasmine Oil', 'botol', 200, 'Suplemen minyak jasmine'),
('Rose Oil', 'botol', 200, 'Suplemen minyak mawar'),
('Neroli Oil', 'botol', 200, 'Suplemen minyak neroli'),
('Yarrow Oil', 'botol', 200, 'Suplemen minyak yarrow'),
('Helichrysum Oil', 'botol', 200, 'Suplemen minyak helichrysum'),
('Clary Sage Oil', 'botol', 200, 'Suplemen minyak clary sage'),
('Marjoram Oil', 'botol', 200, 'Suplemen minyak marjoram'),
('Thyme Oil', 'botol', 200, 'Suplemen minyak thyme'),
('Oregano Oil', 'botol', 200, 'Suplemen minyak oregano'),
('Cinnamon Oil', 'botol', 200, 'Suplemen minyak kayu manis'),
('Clove Oil', 'botol', 200, 'Suplemen minyak cengkeh'),
('Nutmeg Oil', 'botol', 200, 'Suplemen minyak pala'),
('Cardamom Oil', 'botol', 200, 'Suplemen minyak kapulaga'),
('Black Pepper Oil', 'botol', 200, 'Suplemen minyak lada hitam'),
('Ginger Oil', 'botol', 200, 'Suplemen minyak jahe'),
('Turmeric Oil', 'botol', 200, 'Suplemen minyak kunyit'),
('Curcumin', 'kapsul', 400, 'Suplemen kurkumin'),
('Boswellia', 'tablet', 300, 'Suplemen boswellia'),
('Devil\'s Claw', 'tablet', 300, 'Suplemen devil\'s claw'),
('White Willow Bark', 'tablet', 300, 'Suplemen white willow bark'),
('Meadowsweet', 'tablet', 300, 'Suplemen meadowsweet'),
('Feverfew', 'tablet', 300, 'Suplemen feverfew'),
('Butterbur', 'tablet', 300, 'Suplemen butterbur'),
('Passionflower', 'tablet', 300, 'Suplemen passionflower'),
('Valerian', 'tablet', 400, 'Suplemen valerian'),
('Chamomile', 'tablet', 500, 'Suplemen chamomile'),
('Lemon Balm', 'tablet', 400, 'Suplemen lemon balm'),
('Lavender', 'tablet', 400, 'Suplemen lavender'),
('Hops', 'tablet', 300, 'Suplemen hops'),
('Skullcap', 'tablet', 300, 'Suplemen skullcap'),
('Kava', 'tablet', 300, 'Suplemen kava'),
('Ashwagandha', 'tablet', 400, 'Suplemen ashwagandha'),
('Rhodiola', 'tablet', 300, 'Suplemen rhodiola'),
('Holy Basil', 'tablet', 400, 'Suplemen holy basil'),
('Adaptogen Blend', 'tablet', 300, 'Suplemen adaptogen'),
('Maca', 'tablet', 400, 'Suplemen maca'),
('Tribulus', 'tablet', 300, 'Suplemen tribulus'),
('Tongkat Ali', 'tablet', 300, 'Suplemen tongkat ali'),
('Horny Goat Weed', 'tablet', 300, 'Suplemen horny goat weed'),
('Yohimbe', 'tablet', 200, 'Suplemen yohimbe'),
('Muira Puama', 'tablet', 200, 'Suplemen muira puama'),
('Damiana', 'tablet', 300, 'Suplemen damiana'),
('Saw Palmetto', 'tablet', 300, 'Suplemen saw palmetto'),
('Pygcum', 'tablet', 300, 'Suplemen pygcum'),
('Stinging Nettle', 'tablet', 300, 'Suplemen stinging nettle'),
('Horse Chestnut', 'tablet', 300, 'Suplemen horse chestnut'),
('Butcher\'s Broom', 'tablet', 300, 'Suplemen butcher\'s broom'),
('Ginkgo Biloba', 'tablet', 500, 'Suplemen ginkgo biloba'),
('Bacopa', 'tablet', 300, 'Suplemen bacopa'),
('Lion\'s Mane', 'tablet', 300, 'Suplemen lion\'s mane'),
('Reishi', 'tablet', 300, 'Suplemen reishi'),
('Cordyceps', 'tablet', 300, 'Suplemen cordyceps'),
('Chaga', 'tablet', 300, 'Suplemen chaga'),
('Turkey Tail', 'tablet', 300, 'Suplemen turkey tail'),
('Shiitake', 'tablet', 300, 'Suplemen shiitake'),
('Maitake', 'tablet', 300, 'Suplemen maitake'),
('Agaricus', 'tablet', 300, 'Suplemen agaricus'),
('Beta Glucan', 'tablet', 300, 'Suplemen beta glucan'),
('Colostrum', 'kapsul', 300, 'Suplemen kolostrum'),
('Transfer Factor', 'kapsul', 200, 'Suplemen transfer factor'),
('Elderberry', 'tablet', 400, 'Suplemen elderberry'),
('Elderberry Syrup', 'botol', 300, 'Suplemen elderberry'),
('Astragalus', 'tablet', 300, 'Suplemen astragalus'),
('Andrographis', 'tablet', 300, 'Suplemen andrographis'),
('Oregano Oil', 'kapsul', 400, 'Suplemen minyak oregano'),
('Olive Leaf Extract', 'tablet', 300, 'Suplemen ekstrak daun zaitun'),
('Grapefruit Seed Extract', 'tablet', 300, 'Suplemen ekstrak biji jeruk bali'),
('Colloidal Silver', 'botol', 200, 'Suplemen perak koloid'),
('Manuka Honey', 'botol', 200, 'Suplemen madu manuka'),
('Propolis', 'tablet', 300, 'Suplemen propolis'),
('Royal Jelly', 'kapsul', 300, 'Suplemen royal jelly'),
('Bee Pollen', 'tablet', 300, 'Suplemen bee pollen'),
('Spirulina', 'tablet', 400, 'Suplemen spirulina'),
('Chlorella', 'tablet', 300, 'Suplemen chlorella'),
('Kelp', 'tablet', 300, 'Suplemen kelp'),
('Dulse', 'tablet', 300, 'Suplemen dulse'),
('Wakame', 'tablet', 300, 'Suplemen wakame'),
('Nori', 'tablet', 300, 'Suplemen nori'),
('Seaweed', 'tablet', 300, 'Suplemen rumput laut'),
('Sea Buckthorn', 'tablet', 300, 'Suplemen sea buckthorn'),
('Goji Berry', 'tablet', 400, 'Suplemen goji berry'),
('Acai Berry', 'tablet', 300, 'Suplemen acai berry'),
('Maqui Berry', 'tablet', 300, 'Suplemen maqui berry'),
('Camu Camu', 'tablet', 300, 'Suplemen camu camu'),
('Acerola', 'tablet', 300, 'Suplemen acerola'),
('Baobab', 'tablet', 300, 'Suplemen baobab'),
('Mangosteen', 'tablet', 300, 'Suplemen mangosteen'),
('Noni', 'tablet', 300, 'Suplemen noni'),
('Pomegranate', 'tablet', 300, 'Suplemen delima'),
('Pomegranate Extract', 'tablet', 300, 'Suplemen ekstrak delima'),
('Grape Seed Extract', 'tablet', 300, 'Suplemen ekstrak biji anggur'),
('Pine Bark Extract', 'tablet', 300, 'Suplemen ekstrak kulit pinus'),
('Pycnogenol', 'tablet', 300, 'Suplemen pycnogenol'),
('OPC', 'tablet', 300, 'Suplemen OPC'),
('Alpha Lipoic Acid', 'tablet', 300, 'Suplemen alpha lipoic acid'),
('NAC', 'tablet', 300, 'Suplemen NAC'),
('Glutathione', 'tablet', 300, 'Suplemen glutathione'),
('SOD', 'tablet', 300, 'Suplemen SOD'),
('Catalase', 'tablet', 300, 'Suplemen catalase'),
('CoQ10', 'kapsul', 400, 'Suplemen CoQ10'),
('Ubiquinol', 'kapsul', 300, 'Suplemen ubiquinol'),
('PQQ', 'tablet', 300, 'Suplemen PQQ'),
('NADH', 'tablet', 300, 'Suplemen NADH'),
('NAD+', 'tablet', 300, 'Suplemen NAD+'),
('NMN', 'tablet', 300, 'Suplemen NMN'),
('Resveratrol', 'tablet', 300, 'Suplemen resveratrol'),
('Fisetin', 'tablet', 300, 'Suplemen fisetin'),
('Quercetin', 'tablet', 300, 'Suplemen quercetin'),
('Rutin', 'tablet', 300, 'Suplemen rutin'),
('Hesperidin', 'tablet', 300, 'Suplemen hesperidin'),
('Diosmin', 'tablet', 300, 'Suplemen diosmin'),
('Naringin', 'tablet', 300, 'Suplemen naringin'),
('Apigenin', 'tablet', 300, 'Suplemen apigenin'),
('Luteolin', 'tablet', 300, 'Suplemen luteolin'),
('Kaempferol', 'tablet', 300, 'Suplemen kaempferol'),
('Myricetin', 'tablet', 300, 'Suplemen myricetin'),
('Isorhamnetin', 'tablet', 300, 'Suplemen isorhamnetin'),
('Genistein', 'tablet', 300, 'Suplemen genistein'),
('Daidzein', 'tablet', 300, 'Suplemen daidzein'),
('Equol', 'tablet', 300, 'Suplemen equol'),
('Soy Isoflavones', 'tablet', 300, 'Suplemen isoflavon kedelai'),
('Red Clover', 'tablet', 300, 'Suplemen red clover'),
('Black Cohosh', 'tablet', 300, 'Suplemen black cohosh'),
('Dong Quai', 'tablet', 300, 'Suplemen dong quai'),
('Vitex', 'tablet', 300, 'Suplemen vitex'),
('Evening Primrose Oil', 'kapsul', 300, 'Suplemen evening primrose oil'),
('Borage Oil', 'kapsul', 300, 'Suplemen borage oil'),
('Black Currant Oil', 'kapsul', 300, 'Suplemen black currant oil'),
('Starflower Oil', 'kapsul', 300, 'Suplemen starflower oil'),
('Hemp Seed Oil', 'botol', 200, 'Suplemen hemp seed oil'),
('Flaxseed Oil', 'kapsul', 400, 'Suplemen flaxseed oil'),
('Chia Seed Oil', 'botol', 200, 'Suplemen chia seed oil'),
('Pumpkin Seed Oil', 'botol', 200, 'Suplemen pumpkin seed oil'),
('Sunflower Seed Oil', 'botol', 200, 'Suplemen sunflower seed oil'),
('Safflower Oil', 'botol', 200, 'Suplemen safflower oil'),
('Grapeseed Oil', 'botol', 200, 'Suplemen grapeseed oil'),
('Rice Bran Oil', 'botol', 200, 'Suplemen rice bran oil'),
('Wheat Germ Oil', 'botol', 200, 'Suplemen wheat germ oil'),
('Sesame Oil', 'botol', 200, 'Suplemen sesame oil'),
('Peanut Oil', 'botol', 200, 'Suplemen peanut oil'),
('Almond Oil', 'botol', 200, 'Suplemen almond oil'),
('Walnut Oil', 'botol', 200, 'Suplemen walnut oil'),
('Hazelnut Oil', 'botol', 200, 'Suplemen hazelnut oil'),
('Macadamia Oil', 'botol', 200, 'Suplemen macadamia oil'),
('Pistachio Oil', 'botol', 200, 'Suplemen pistachio oil'),
('Pecan Oil', 'botol', 200, 'Suplemen pecan oil'),
('Brazil Nut Oil', 'botol', 200, 'Suplemen brazil nut oil'),
('Cashew Oil', 'botol', 200, 'Suplemen cashew oil'),
('Coconut Oil', 'botol', 400, 'Suplemen coconut oil'),
('MCT Oil', 'botol', 200, 'Suplemen MCT oil'),
('Palm Oil', 'botol', 200, 'Suplemen palm oil'),
('Red Palm Oil', 'botol', 200, 'Suplemen red palm oil'),
('Palm Kernel Oil', 'botol', 200, 'Suplemen palm kernel oil'),
('Shea Butter', 'botol', 200, 'Suplemen shea butter'),
('Cocoa Butter', 'botol', 200, 'Suplemen cocoa butter'),
('Mango Butter', 'botol', 200, 'Suplemen mango butter'),
('Avocado Oil', 'botol', 300, 'Suplemen avocado oil'),
('Olive Oil', 'botol', 300, 'Suplemen olive oil'),
('Extra Virgin Olive Oil', 'botol', 300, 'Suplemen extra virgin olive oil'),
('Virgin Olive Oil', 'botol', 300, 'Suplemen virgin olive oil'),
('Light Olive Oil', 'botol', 300, 'Suplemen light olive oil'),
('Pomace Olive Oil', 'botol', 300, 'Suplemen pomace olive oil'),
('Canola Oil', 'botol', 200, 'Suplemen canola oil'),
('Rapeseed Oil', 'botol', 200, 'Suplemen rapeseed oil'),
('Mustard Oil', 'botol', 200, 'Suplemen mustard oil'),
('Cottonseed Oil', 'botol', 200, 'Suplemen cottonseed oil'),
('Soybean Oil', 'botol', 200, 'Suplemen soybean oil'),
('Corn Oil', 'botol', 200, 'Suplemen corn oil'),
('Vegetable Oil', 'botol', 200, 'Suplemen vegetable oil'),
('Shortening', 'botol', 200, 'Suplemen shortening'),
('Lard', 'botol', 200, 'Suplemen lard'),
('Tallow', 'botol', 200, 'Suplemen tallow'),
('Ghee', 'botol', 300, 'Suplemen ghee'),
('Clarified Butter', 'botol', 300, 'Suplemen clarified butter'),
('Butter', 'botol', 300, 'Suplemen butter'),
('Margarine', 'botol', 200, 'Suplemen margarine'),
('Vegetable Shortening', 'botol', 200, 'Suplemen vegetable shortening'),
('Crisco', 'botol', 200, 'Suplemen crisco'),
('Lard', 'botol', 200, 'Suplemen lard'),
('Suet', 'botol', 200, 'Suplemen suet'),
('Dripping', 'botol', 200, 'Suplemen dripping'),
('Schmaltz', 'botol', 200, 'Suplemen schmaltz'),
('Goose Fat', 'botol', 200, 'Suplemen goose fat'),
('Duck Fat', 'botol', 200, 'Suplemen duck fat'),
('Chicken Fat', 'botol', 200, 'Suplemen chicken fat'),
('Beef Fat', 'botol', 200, 'Suplemen beef fat'),
('Pork Fat', 'botol', 200, 'Suplemen pork fat'),
('Lamb Fat', 'botol', 200, 'Suplemen lamb fat');

